[spec]

; Epoch sprites — GENERATED by tools/art/make_sheet.ts from epoch_extras.json.
; Regenerate with:  cd tools/art && npm run sheet -- --manifest sheets/epoch_extras.json

options = "+Freeciv-spec-3.3-Devel-2023.Apr.05"

[info]

artists = "
    Epoch project (fal.ai Nano Banana 2 generations; see tools/art/README.md)
"

[file]
gfx = "amplio2/epoch_extras"

[grid_main]

x_top_left = 0
y_top_left = 0
dx = 96
dy = 48
pixel_border = 0

tiles = { "row", "column", "tag"
  0, 0, "extra.kelp_farm"
  0, 1, "road.sea_tunnel_n"
  0, 2, "road.sea_tunnel_e"
  0, 3, "road.sea_tunnel_s"
  0, 4, "road.sea_tunnel_w"
  1, 0, "road.sea_tunnel_ne"
  1, 1, "road.sea_tunnel_se"
  1, 2, "road.sea_tunnel_sw"
  1, 3, "road.sea_tunnel_nw"
  1, 4, "road.sea_tunnel_isolated"
  2, 0, "extra.solar_array"
  2, 1, "extra.vertical_farm"
  2, 2, "extra.rewilding_grove"
}
