[spec]

; Epoch sprites — GENERATED by tools/art/make_sheet.ts from epoch_units.json.
; Regenerate with:  cd tools/art && npm run sheet -- --manifest sheets/epoch_units.json

options = "+Freeciv-spec-3.3-Devel-2023.Apr.05"

[info]

artists = "
    Epoch project (fal.ai Nano Banana 2 generations; see tools/art/README.md)
"

[file]
gfx = "amplio2/epoch_units"

[grid_main]

x_top_left = 0
y_top_left = 0
dx = 96
dy = 80
pixel_border = 0

tiles = { "row", "column", "tag"
  0, 0, "u.undersea_worker_Idle"
  0, 1, "u.undersea_worker_Idle_0"
  0, 2, "u.undersea_worker_Idle_1"
  0, 3, "u.abyssal_founder_Idle"
  1, 0, "u.weapon_platform_Idle"
  1, 1, "u.weapon_platform_Idle_0"
  1, 2, "u.weapon_platform_Idle_1"
}
