[spec]

; Epoch sprites — GENERATED by tools/art/make_sheet.ts from epoch_buildings.json.
; Regenerate with:  cd tools/art && npm run sheet -- --manifest sheets/epoch_buildings.json

options = "+Freeciv-spec-3.3-Devel-2023.Apr.05"

[info]

artists = "
    Epoch project (fal.ai Nano Banana 2 generations; see tools/art/README.md)
"

[file]
gfx = "amplio2/epoch_buildings"

[grid_main]

x_top_left = 0
y_top_left = 0
dx = 128
dy = 128
pixel_border = 0

tiles = { "row", "column", "tag"
  0, 0, "b.abyssal_foundry"
  0, 1, "b.world_tree_spire"
  0, 2, "b.aquaculture_bay"
  0, 3, "b.deep_habitat"
  1, 0, "b.verdant_engine"
  1, 1, "b.ascendant_nexus"
  1, 2, "b.skyhook_terminus"
  1, 3, "b.gaia_compact"
  2, 0, "b.abyssal_archive"
}
