[spec]

; Epoch sprites — GENERATED by tools/art/make_sheet.ts from epoch_units.json.
; Regenerate with:  cd tools/art && npm run sheet -- --manifest sheets/epoch_units.json

options = "+Freeciv-spec-3.3-Devel-2023.Apr.05"

[info]

artists = "
    Epoch project (fal.ai Nano Banana 2 generations; see tools/art/README.md)
"

[file]
gfx = "amplio2/epoch_units"

[grid_main]

x_top_left = 0
y_top_left = 0
dx = 96
dy = 80
pixel_border = 0

tiles = { "row", "column", "tag"
  0, 0, "u.undersea_worker_Idle"
  0, 1, "u.undersea_worker_Idle_0"
  0, 2, "u.undersea_worker_Idle_1"
  0, 3, "u.abyssal_founder_Idle"
  0, 4, "u.abyssal_founder_Idle_0"
  0, 5, "u.abyssal_founder_Idle_1"
  1, 0, "u.weapon_platform_Idle"
  1, 1, "u.weapon_platform_Idle_0"
  1, 2, "u.weapon_platform_Idle_1"
  1, 3, "u.cyborg_infantry_Idle"
  1, 4, "u.cyborg_infantry_Idle_0"
  1, 5, "u.cyborg_infantry_Idle_1"
  2, 0, "u.chimera_soldier_Idle"
  2, 1, "u.chimera_soldier_Idle_0"
  2, 2, "u.chimera_soldier_Idle_1"
  2, 3, "u.combat_drone_Idle"
  2, 4, "u.combat_drone_Idle_0"
  2, 5, "u.combat_drone_Idle_1"
  3, 0, "u.pressure_sub_Idle"
  3, 1, "u.pressure_sub_Idle_0"
  3, 2, "u.pressure_sub_Idle_1"
  3, 3, "u.war_walker_Idle"
  3, 4, "u.war_walker_Idle_0"
  3, 5, "u.war_walker_Idle_1"
  4, 0, "u.plasma_trooper_Idle"
  4, 1, "u.plasma_trooper_Idle_0"
  4, 2, "u.plasma_trooper_Idle_1"
  4, 3, "u.synthetic_legion_Idle"
  4, 4, "u.synthetic_legion_Idle_0"
  4, 5, "u.synthetic_legion_Idle_1"
  5, 0, "u.plasma_cruiser_Idle"
  5, 1, "u.plasma_cruiser_Idle_0"
  5, 2, "u.plasma_cruiser_Idle_1"
  5, 3, "u.space_plane_Idle"
  5, 4, "u.space_plane_Idle_0"
  5, 5, "u.space_plane_Idle_1"
  6, 0, "u.orbital_interceptor_Idle"
  6, 1, "u.orbital_interceptor_Idle_0"
  6, 2, "u.orbital_interceptor_Idle_1"
}
