/**
 * Compose processed sprites into a tileset sheet PNG + matching freeciv .spec file.
 *
 * Reads a manifest JSON:
 *   {
 *     "cell": "96x80",                      // uniform cell size (dx x dy)
 *     "gfx": "amplio2/epoch_units",         // [file] gfx path as freeciv data-relative
 *     "out": "../../tileset/epoch/web/epoch_units",   // writes <out>.png + <out>.spec
 *     "columns": 4,
 *     "sprites": [
 *       { "tag": "u.undersea_worker_Idle", "file": "../../tileset/epoch/src/units/undersea_worker_96.png" },
 *       ...
 *     ]
 *   }
 *
 * Each sprite must already be exactly cell-sized (process_sprite --pad WxH).
 * The emitted .spec uses [grid_main] with pixel_border=0 so img-extract's
 * cell-size-agnostic packer (reads dx/dy per grid section) picks it up directly.
 *
 * Usage:  npm run sheet -- --manifest sheets/epoch_units.json
 */
import fs from "fs";
import path from "path";
import { PNG } from "pngjs";

const args = process.argv.slice(2);
const mi = args.indexOf("--manifest");
if (mi === -1 || !args[mi + 1]) {
  console.error("--manifest <json> required");
  process.exit(1);
}
const manifestPath = path.isAbsolute(args[mi + 1]) ? args[mi + 1] : path.join(process.cwd(), args[mi + 1]);
const manifestDir = path.dirname(manifestPath);

interface SpriteEntry { tag: string; file: string; }
interface Manifest { cell: string; gfx: string; out: string; columns?: number; sprites: SpriteEntry[]; }

const man: Manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
const m = man.cell.match(/^(\d+)x(\d+)$/i);
if (!m) { console.error(`bad cell "${man.cell}"`); process.exit(1); }
const dx = Number(m[1]), dy = Number(m[2]);
const cols = man.columns ?? 4;
const rows = Math.ceil(man.sprites.length / cols);

const sheet = new PNG({ width: cols * dx, height: rows * dy });
sheet.data = Buffer.alloc(sheet.width * sheet.height * 4);

const specRows: string[] = [];
man.sprites.forEach((s, i) => {
  const fp = path.isAbsolute(s.file) ? s.file : path.join(manifestDir, s.file);
  const img = PNG.sync.read(fs.readFileSync(fp));
  if (img.width !== dx || img.height !== dy) {
    console.error(`${s.tag}: ${img.width}x${img.height} != cell ${dx}x${dy} (${fp})`);
    process.exit(1);
  }
  const row = Math.floor(i / cols), col = i % cols;
  PNG.bitblt(img, sheet, 0, 0, dx, dy, col * dx, row * dy);
  specRows.push(`  ${row}, ${col}, "${s.tag}"`);
  console.log(`placed ${s.tag} @ row ${row}, col ${col}`);
});

const outBase = path.isAbsolute(man.out) ? man.out : path.join(manifestDir, man.out);
fs.mkdirSync(path.dirname(outBase), { recursive: true });
fs.writeFileSync(outBase + ".png", PNG.sync.write(sheet));

const specName = path.basename(outBase);
const spec = `
[spec]

; Epoch sprites — GENERATED by tools/art/make_sheet.ts from ${path.basename(manifestPath)}.
; Regenerate with:  cd tools/art && npm run sheet -- --manifest sheets/${path.basename(manifestPath)}

options = "+Freeciv-spec-3.3-Devel-2023.Apr.05"

[info]

artists = "
    Epoch project (fal.ai Nano Banana 2 generations; see tools/art/README.md)
"

[file]
gfx = "${man.gfx}"

[grid_main]

x_top_left = 0
y_top_left = 0
dx = ${dx}
dy = ${dy}
pixel_border = 0

tiles = { "row", "column", "tag"
${specRows.join("\n")}
}
`.trimStart();
fs.writeFileSync(outBase + ".spec", spec);
console.log(`wrote ${outBase}.png (${sheet.width}x${sheet.height}) + ${specName}.spec (${man.sprites.length} tags)`);
